"use client";
import { useEffect, useState, useRef } from "react";
import { ArrowRight, Check, ChevronLeft, CreditCard, MapPin, ShieldCheck, TicketPercent, Truck } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Checkbox } from "@/components/ui/checkbox";
import { Dialog, DialogContent, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { NativeSelect, NativeSelectOption } from "@/components/ui/native-select";
import { type Address, type CartLine, type Profile, type SavedAddress, type Settings, EMPTY_ADDRESS, lineUnitPrice, money, totals } from "@/lib/shop";
import { ShopApi, errorMessage } from "@/lib/supabase";
import { Field, ProductImage } from "./shared";

export function AddressFields({ address:a, onChange:set, shipping = true }: { address: Address; onChange: (a:Address)=>void; shipping?: boolean }) {
  function field(key:keyof Address,label:string,props:Record<string,unknown>={}) {return <Field key={key} label={label}><Input value={a[key]||""} onChange={e=>set({...a,[key]:e.target.value})} maxLength={150} {...props}/></Field>;}
  return <div className="form-grid">{field("full_name","Nome e cognome",{required:true,minLength:2,autoComplete:"name"})}{field("phone","Telefono",{required:true,minLength:6,maxLength:40,type:"tel",autoComplete:"tel"})}{shipping&&<>{field("street","Indirizzo e numero civico",{required:true,minLength:4,autoComplete:"street-address"})}{field("city","Città",{required:true,minLength:2,autoComplete:"address-level2"})}{field("postal_code","CAP",{required:true,pattern:"[0-9]{5}",maxLength:5,inputMode:"numeric",autoComplete:"postal-code"})}<Field label="Paese"><Input value="Italia" readOnly /></Field></>}{field("company","Azienda (facoltativo)",{autoComplete:"organization"})}{field("tax_id","P. IVA / codice fiscale (facoltativo)",{maxLength:25})}</div>;
}
export function Checkout({ api, profile, lines, settings, onClose, onCreated }: { api:ShopApi; profile:Profile; lines:CartLine[]; settings:Settings; onClose:()=>void; onCreated:(id:string)=>Promise<void> }) {
  const [step,setStep] = useState(1); const [address,setAddress] = useState<Address>({...EMPTY_ADDRESS,full_name:profile.full_name,phone:profile.phone||""});
  const [addresses,setAddresses]=useState<SavedAddress[]>([]); const [delivery,setDelivery]=useState<"shipping"|"pickup">("shipping"); const [payment,setPayment]=useState("manual");
  const [note,setNote]=useState(""); const [gift,setGift]=useState(""); const [save,setSave]=useState(false); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  const [coupon,setCoupon]=useState(""); const [discount,setDiscount]=useState<{code:string;percent:number;min:number}|null>(null); const [checking,setChecking]=useState(false);
  const requestId=useRef(crypto.randomUUID()); const submitted=useRef(false);
  useEffect(()=>{api.addresses().then(setAddresses).catch(e=>toast.error(errorMessage(e)));},[api]);
  const sum=totals(lines,settings,delivery,discount?.percent||0);
  const invalid=lines.some(l=>l.quantity>l.product.stock||!l.product.is_active||l.product.purchase_mode==="quote");
  async function submit() {
    if(submitted.current) return; submitted.current=true; setBusy(true);setError("");
    try {
      if(invalid) throw new Error("La disponibilità di un articolo è cambiata. Aggiorna il carrello.");
      const result=await api.placeOrder({items:lines.map(l=>({product_id:l.product_id,quantity:l.quantity})),address,delivery,payment,coupon:discount?.code||"",note,gift,requestId:requestId.current});
      try { await api.notifyOrder(result.id,"order_created"); } catch { /* L’ordine resta valido anche se il servizio email non è configurato. */ }
      if(save&&delivery==="shipping") {try{await api.saveAddress(address);}catch{toast.info("Ordine salvato. Non è stato possibile aggiungere l’indirizzo alla rubrica.");}}
      await onCreated(result.id);
      if(payment==="stripe") {try{const r=await api.server<{url:string}>("/api/checkout",{orderId:result.id});window.location.assign(r.url);}catch(e){toast.error(`Ordine creato, pagamento non avviato: ${errorMessage(e)}. Riprendi dalla cronologia ordini.`,{duration:9000});}}
    }catch(e){setError(errorMessage(e));submitted.current=false;}finally{setBusy(false);}
  }
  return <Dialog open onOpenChange={v=>!v&&!busy&&onClose()}><DialogContent className="checkout-modal modal" onInteractOutside={e=>busy&&e.preventDefault()} onEscapeKeyDown={e=>busy&&e.preventDefault()} showCloseButton={!busy}><div className="checkout-head"><span className="eyebrow">IL TUO ORDINE</span><DialogTitle>Un ultimo passo. Poi ci pensiamo noi.</DialogTitle><DialogDescription>Consegna, pagamento e riepilogo in un unico posto.</DialogDescription><ol className="checkout-steps"><li className={step>=1?"active":""}><span>{step>1?<Check size={14}/>:"1"}</span> Consegna</li><li className={step>=2?"active":""}><span>2</span> Riepilogo</li></ol></div>
    <div className="checkout-layout"><div>{step===1?<form className="form-stack" onSubmit={e=>{e.preventDefault();setError("");setStep(2);}}><div className="delivery-options"><button type="button" className={delivery==="shipping"?"selected":""} onClick={()=>{setDelivery("shipping");if(payment==="pickup")setPayment("manual");}}><Truck size={22}/><b>Spedizione</b><span>Consegna in Italia</span></button>{settings.pickup_enabled&&<button type="button" className={delivery==="pickup"?"selected":""} onClick={()=>setDelivery("pickup")}><MapPin size={22}/><b>Ritiro in sede</b><span>{settings.pickup_address||"Da concordare con lo staff"}</span></button>}</div>
      {addresses.length>0&&delivery==="shipping"&&<Field label="Usa un indirizzo salvato"><NativeSelect defaultValue="" onChange={e=>{const a=addresses.find(a=>a.id===e.target.value);if(a)setAddress({full_name:a.full_name,phone:a.phone,street:a.street,city:a.city,postal_code:a.postal_code,country:a.country,company:a.company||"",tax_id:a.tax_id||""});}}><NativeSelectOption value="">Inserisci un nuovo indirizzo</NativeSelectOption>{addresses.map(a=><NativeSelectOption key={a.id} value={a.id}>{a.street}, {a.city}</NativeSelectOption>)}</NativeSelect></Field>}
      <AddressFields address={address} onChange={setAddress} shipping={delivery==="shipping"}/>{delivery==="shipping"&&<label className="check-label"><Checkbox checked={save} onCheckedChange={v=>setSave(v===true)}/> Salva questo indirizzo nel mio account</label>}<Button className="btn" type="submit">Continua al riepilogo <ArrowRight size={17}/></Button></form>:<div className="form-stack"><button className="text-button" onClick={()=>setStep(1)}><ChevronLeft size={16}/> Modifica consegna</button><div className="address-summary"><MapPin size={20}/><div><strong>{address.full_name}</strong><p>{delivery==="pickup"?`Ritiro: ${settings.pickup_address||"da concordare"}`:`${address.street}, ${address.postal_code} ${address.city}`}</p><p>{address.phone}</p></div></div><h3>Come preferisci pagare?</h3><div className="payment-options">
        {[{id:"manual",title:"Ordine da confermare",desc:"Invia la richiesta: concordi il pagamento con lo staff. Nessun addebito online."},...(settings.bank_enabled?[{id:"bank_transfer",title:"Bonifico bancario",desc:"Le coordinate saranno disponibili nel dettaglio ordine."}]:[]),...(delivery==="pickup"?[{id:"pickup",title:"Pagamento al ritiro",desc:"Paghi quando ritiri il tuo ordine."}]:[]),...(settings.card_enabled?[{id:"stripe",title:"Carta di credito o debito",desc:"Prosegui al pagamento sicuro su Stripe."}]:[])].map(m=><label className={payment===m.id?"payment-option selected":"payment-option"} key={m.id}><input type="radio" name="payment" value={m.id} checked={payment===m.id} onChange={()=>setPayment(m.id)}/><span><b>{m.title}</b><small>{m.desc}</small></span>{m.id==="stripe"&&<CreditCard size={20}/>}</label>)}
      </div><Field label="Note per lo staff (facoltativo)"><textarea maxLength={2000} value={note} onChange={e=>setNote(e.target.value)} placeholder="Citofono, orari preferiti, richieste particolari…"/></Field><Field label="Messaggio regalo (facoltativo)"><Input maxLength={500} value={gift} onChange={e=>setGift(e.target.value)} placeholder="Una dedica per chi riceve il pacco"/></Field>{error&&<p className="notice error" role="alert">{error}</p>}<Button className="btn full btn-lg" onClick={submit} disabled={busy||invalid}>{busy?"Creazione ordine…":payment==="stripe"?`Prosegui al pagamento · ${money(sum.total)}`:`Conferma ordine · ${money(sum.total)}`}<ArrowRight size={18}/></Button><p className="muted small"><ShieldCheck size={15}/> Prezzi, sconti e disponibilità vengono ricontrollati alla conferma.</p></div>}</div>
      <aside className="checkout-summary"><h3>La tua selezione <span>({lines.reduce((n,l)=>n+l.quantity,0)})</span></h3><div className="summary-lines">{lines.map(l=><div className="summary-line" key={l.product_id}><ProductImage product={l.product}/><div><b>{l.product.name}</b><span>{l.quantity} × {money(lineUnitPrice(l.product,l.quantity))}</span></div><strong>{money(lineUnitPrice(l.product,l.quantity)*l.quantity)}</strong></div>)}</div><form className="coupon-form" onSubmit={async e=>{e.preventDefault();setChecking(true);try{const c=await api.coupon(coupon,sum.subtotal);setDiscount({code:c.code,percent:c.percent_off,min:c.min_amount});toast.success("Codice applicato");}catch(e){setDiscount(null);toast.error(errorMessage(e));}finally{setChecking(false);}}}><TicketPercent size={19}/><Input aria-label="Codice sconto" placeholder="Codice sconto" value={coupon} onChange={e=>setCoupon(e.target.value.toUpperCase())} maxLength={30}/><Button className="btn btn-outline" disabled={checking||!coupon}>Applica</Button></form>{discount&&<p className="coupon-applied">{discount.code} · −{discount.percent}% <button onClick={()=>{setDiscount(null);setCoupon("");}}>Rimuovi</button></p>}<div className="totals"><div><span>Prodotti</span><b>{money(sum.subtotal)}</b></div>{sum.discount>0&&<div><span>Sconto</span><b>−{money(sum.discount)}</b></div>}<div><span>{delivery==="pickup"?"Ritiro":"Spedizione"}</span><b>{sum.shipping?money(sum.shipping):"Gratuita"}</b></div><div className="grand-total"><span>Totale</span><b>{money(sum.total)}</b></div></div>{invalid&&<p className="notice error">La disponibilità è cambiata: torna al carrello per correggere le quantità.</p>}</aside>
    </div></DialogContent></Dialog>;
}
