"use client";
import { useEffect, useState } from "react";
import { ArrowRight, Box, CheckCircle2, ClipboardList, KeyRound, LogOut, MapPin, RefreshCw, Trash2, UserRound } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Dialog, DialogContent, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { AlertDialog, AlertDialogContent, AlertDialogHeader, AlertDialogTitle, AlertDialogDescription, AlertDialogFooter, AlertDialogCancel, AlertDialogAction } from "@/components/ui/alert-dialog";
import { type Order, type Profile, type Quote, type SavedAddress, type Settings, date, money, orderNumber, ORDER_STATUS, PAYMENT_STATUS, safeLink } from "@/lib/shop";
import { ShopApi, errorMessage } from "@/lib/supabase";
import { Empty, Field } from "./shared";

export function OrderDetail({ order:o, settings, onClose }: { order:Order; settings:Settings; onClose:()=>void }) {
  const phases=["pending","confirmed","preparing","shipped","completed"];const index=phases.indexOf(o.status);
  return <Dialog open onOpenChange={v=>!v&&onClose()}><DialogContent className="order-modal modal"><span className="eyebrow">IL TUO ORDINE</span><DialogTitle>{orderNumber(o.id)}</DialogTitle><DialogDescription>{date(o.created_at)} · {ORDER_STATUS[o.status]} · {PAYMENT_STATUS[o.payment_status]}</DialogDescription>
    {o.status!=="cancelled"&&<ol className="order-timeline">{phases.map((s,i)=><li key={s} className={index>=i?"done":""}><span>{index>=i?<CheckCircle2 size={17}/>:i+1}</span><small>{ORDER_STATUS[s]}</small></li>)}</ol>}
    <div className="order-items">{o.order_items.map((l,i)=><div key={i}><span><b>{l.product_name}</b><small>{l.quantity} × {money(Number(l.unit_price))}</small></span><strong>{money(l.quantity*l.unit_price)}</strong></div>)}</div>
    <div className="totals"><div><span>Spedizione / ritiro</span><b>{money(Number(o.shipping_amount||0))}</b></div>{Number(o.discount_amount)>0&&<div><span>Sconto {o.coupon_code}</span><b>−{money(Number(o.discount_amount))}</b></div>}<div className="grand-total"><span>Totale ordine</span><b>{money(Number(o.total_amount))}</b></div></div>
    {o.shipping_address&&<div className="address-summary"><MapPin size={19}/><div><b>{o.shipping_address.full_name}</b><p>{o.delivery_method==="pickup"?`Ritiro: ${settings.pickup_address||"da concordare"}`:`${o.shipping_address.street}, ${o.shipping_address.postal_code} ${o.shipping_address.city}`}</p><p>{o.shipping_address.phone}</p>{o.shipping_address.company&&<p>{o.shipping_address.company} · {o.shipping_address.tax_id}</p>}</div></div>}
    {o.note&&<p className="note-box"><b>Note</b><br/>{o.note}</p>}{o.gift_message&&<p className="note-box"><b>Messaggio regalo</b><br/>{o.gift_message}</p>}
    {o.payment_provider==="bank_transfer"&&o.payment_status!=="paid"&&o.status!=="cancelled"&&<div className="notice"><b>Pagamento tramite bonifico</b><p className="preserve-lines">{settings.bank_details||"Contatta lo staff per le coordinate."}</p><p>Causale: {orderNumber(o.id)}. Il pagamento viene confermato dallo staff dopo la verifica dell’accredito.</p></div>}
    {safeLink(o.tracking_url)&&<a className="btn full" href={safeLink(o.tracking_url)!} target="_blank" rel="noopener noreferrer">Segui la spedizione <ArrowRight size={17}/></a>}
  </DialogContent></Dialog>;
}
export function Account({ api, profile, orders, settings, onProfile, onRefresh, onReorder, onLogout }: { api:ShopApi; profile:Profile; orders:Order[]; settings:Settings; onProfile:(p:Profile)=>void; onRefresh:()=>Promise<void>; onReorder:(o:Order)=>Promise<void>; onLogout:()=>void }) {
  const [tab,setTab]=useState("orders");const [detail,setDetail]=useState<Order|null>(null); const [cancel,setCancel]=useState<Order|null>(null);
  const [name,setName]=useState(profile.full_name);const [phone,setPhone]=useState(profile.phone||"");const [busy,setBusy]=useState(false);
  const [addresses,setAddresses]=useState<SavedAddress[]>([]); const [quotes,setQuotes]=useState<Quote[]>([]);
  useEffect(()=>{Promise.all([api.addresses(),api.quotes()]).then(([a,q])=>{setAddresses(a);setQuotes(q.filter(x=>x.user_id===profile.id));}).catch(e=>toast.error(errorMessage(e)));},[api,profile.id]);
  const own=orders.filter(o=>o.user_id===profile.id);
  return <section className="account-page page-wrap"><div className="page-heading"><div><span className="eyebrow">IL TUO SPAZIO JOLLY</span><h1>Ciao, {profile.full_name.split(" ")[0]}<em>.</em></h1><p>Tutti i tuoi ordini, le tue richieste e i tuoi dati.</p></div><Button className="btn btn-outline" onClick={onLogout}><LogOut size={17}/> Esci</Button></div>
    <Tabs value={tab} onValueChange={setTab}><TabsList className="section-tabs"><TabsTrigger value="orders"><ClipboardList size={17}/> I miei ordini <span>{own.length}</span></TabsTrigger><TabsTrigger value="quotes"><Box size={17}/> Preventivi</TabsTrigger><TabsTrigger value="profile"><UserRound size={17}/> Profilo e indirizzi</TabsTrigger></TabsList></Tabs>
    {tab==="orders"&&<div className="account-orders">{own.length===0?<Empty title="Il primo ordine ti aspetta" description="Quando effettui un ordine, qui puoi seguirne lo stato e ripeterlo in pochi passaggi."/>:own.map(o=><article className="order-card" key={o.id}><div className="order-card-top"><div><span className="muted small">{date(o.created_at)}</span><h3>{orderNumber(o.id)}</h3></div><span className={`status-tag status-${o.status}`}>{ORDER_STATUS[o.status]}</span></div><p>{o.order_items.map(l=>`${l.quantity} × ${l.product_name}`).join(" · ")}</p><div className="order-card-bottom"><div><strong>{money(Number(o.total_amount))}</strong><span className="muted small">{PAYMENT_STATUS[o.payment_status]}</span></div><div className="order-actions"><Button className="btn btn-outline" onClick={()=>setDetail(o)}>Dettagli <ArrowRight size={15}/></Button><Button className="btn btn-soft" disabled={busy} onClick={async()=>{setBusy(true);try{await onReorder(o);}finally{setBusy(false);}}}><RefreshCw size={15}/> Riordina</Button>
      {o.status==="pending"&&o.payment_status!=="paid"&&o.payment_provider!=="stripe"&&<button className="text-button danger" onClick={()=>setCancel(o)}>Annulla</button>}
      {o.status==="pending"&&o.payment_status!=="paid"&&o.payment_provider==="stripe"&&<Button className="btn" disabled={busy} onClick={async()=>{setBusy(true);try{const r=await api.server<{url:string}>("/api/checkout",{orderId:o.id});window.location.assign(r.url);}catch(e){toast.error(errorMessage(e));}finally{setBusy(false);}}}>Riprendi pagamento</Button>}
    </div></div></article>)}</div>}
    {tab==="quotes"&&<div className="account-orders">{quotes.length?quotes.map(q=><article className="order-card" key={q.id}><div className="order-card-top"><h3>{q.product_name}</h3><span className="status-tag">{q.status==="new"?"Richiesta inviata":q.status==="contacted"?"In contatto":"Chiusa"}</span></div><p>{q.message}</p><span className="muted small">{date(q.created_at)} · {q.phone}</span></article>):<Empty icon={<Box size={32}/>} title="Nessuna richiesta di preventivo" description="Per le attrezzature su preventivo, invia la tua richiesta dalla scheda articolo."/>}</div>}
    {tab==="profile"&&<div className="profile-grid"><form className="panel form-stack" onSubmit={async e=>{e.preventDefault();setBusy(true);try{await api.saveProfile(name,phone);onProfile({...profile,full_name:name,phone});toast.success("Profilo aggiornato");}catch(e){toast.error(errorMessage(e));}finally{setBusy(false);}}}><h2>I tuoi dati</h2><Field label="Nome e cognome"><Input value={name} onChange={e=>setName(e.target.value)} required minLength={2} maxLength={120}/></Field><Field label="Email di accesso"><Input value={profile.email||api.session?.user.email||""} readOnly /></Field><Field label="Telefono"><Input type="tel" value={phone} maxLength={40} onChange={e=>setPhone(e.target.value)}/></Field><Button className="btn" disabled={busy}>Salva modifiche</Button><button className="text-button" type="button" disabled={busy} onClick={async()=>{setBusy(true);try{await api.reset(api.session!.user.email);toast.success("Email di recupero password inviata");}catch(e){toast.error(errorMessage(e));}finally{setBusy(false);}}}><KeyRound size={17}/> Cambia password tramite email</button></form><div className="panel"><h2>Indirizzi salvati</h2><p className="muted">Puoi aggiungere un indirizzo durante il checkout.</p>{addresses.length===0?<p className="note-box">Non hai ancora salvato un indirizzo.</p>:addresses.map(a=><div className="address-summary" key={a.id}><MapPin size={20}/><div><b>{a.full_name}</b><p>{a.street}<br/>{a.postal_code} {a.city}</p><small>{a.phone}</small></div><button className="icon-btn danger" disabled={busy} aria-label={`Rimuovi indirizzo ${a.street}`} onClick={async()=>{setBusy(true);try{await api.removeAddress(a.id);setAddresses(addresses.filter(x=>x.id!==a.id));toast.success("Indirizzo rimosso");}catch(e){toast.error(errorMessage(e));}finally{setBusy(false);}}}><Trash2 size={17}/></button></div>)}</div></div>}
    {detail&&<OrderDetail order={detail} settings={settings} onClose={()=>setDetail(null)}/>}
    <AlertDialog open={!!cancel} onOpenChange={v=>!v&&setCancel(null)}><AlertDialogContent className="modal"><AlertDialogHeader><AlertDialogTitle>Annullare questo ordine?</AlertDialogTitle><AlertDialogDescription>I prodotti torneranno disponibili in magazzino. Potrai effettuare un nuovo ordine in seguito.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Indietro</AlertDialogCancel><AlertDialogAction className="btn" disabled={busy} onClick={async()=>{if(!cancel)return;setBusy(true);try{await api.cancelOrder(cancel.id);await onRefresh();toast.success("Ordine annullato");setCancel(null);}catch(e){toast.error(errorMessage(e));}finally{setBusy(false);}}}>Conferma annullamento</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </section>;
}
