"use client";
import { useCallback, useEffect, useState, type FormEvent } from "react";
import { ArrowLeft, ArrowUpRight, BadgePercent, Boxes, Check, ClipboardList, Download, Eye, LayoutDashboard, MailPlus, Package, Pencil, Plus, RefreshCw, Search, Settings2, ShieldCheck, Upload, Users } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Checkbox } from "@/components/ui/checkbox";
import { Switch } from "@/components/ui/switch";
import { Dialog, DialogContent, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { NativeSelect, NativeSelectOption as Option } from "@/components/ui/native-select";
import { type Coupon, type Order, type Product, type Profile, type Quote, type Settings, CATEGORIES, date, downloadCsv, money, ORDER_STATUS, PAYMENT_STATUS, orderNumber, safeImage } from "@/lib/shop";
import { ShopApi, errorMessage } from "@/lib/supabase";
import { Brand, Empty, Field, ProductImage } from "./shared";
import { OrderDetail } from "./account";

const decimal=(s:string)=>Number(s.replace(",","."));
function ProductEditor({ api, product:p, onClose, onSaved }: { api:ShopApi; product:Product|null; onClose:()=>void; onSaved:()=>Promise<void> }) {
  const [name,setName]=useState(p?.name||"");const [category,setCategory]=useState(p?.category||"Caramelle");const [price,setPrice]=useState(p?String(p.price):"");const [oldPrice,setOldPrice]=useState(p?.compare_at_price?String(p.compare_at_price):"");const [stock,setStock]=useState(String(p?.stock??0));
  const [description,setDescription]=useState(p?.description||"");const [image,setImage]=useState(p?.image_url||"");const [sku,setSku]=useState(p?.sku||"");const [weight,setWeight]=useState(p?.weight_label||"");const [ingredients,setIngredients]=useState(p?.ingredients||"");const [allergens,setAllergens]=useState(p?.allergens||"");const [badge,setBadge]=useState(p?.badge||"");
  const [featured,setFeatured]=useState(p?.featured||false);const [active,setActive]=useState(p?.is_active??true);const [mode,setMode]=useState(p?.purchase_mode||"buy");const [busy,setBusy]=useState(false);const [error,setError]=useState("");
  async function submit(e:FormEvent){e.preventDefault();setError("");const n=decimal(price||"0"),s=Number(stock),old=oldPrice?decimal(oldPrice):null;
    if(!Number.isFinite(n)||n<0||(mode==="buy"&&n<.01)||!Number.isInteger(s)||s<0||(old!==null&&(!Number.isFinite(old)||old<=n))){setError("Verifica prezzo, prezzo precedente (deve essere maggiore) e stock (intero, da zero in su).");return;}
    if(image&&!safeImage(image)){setError("Inserisci un URL HTTPS valido oppure carica un’immagine.");return;}
    setBusy(true);try{await api.saveProduct({name:name.trim(),slug:p?.slug||`${name.trim().toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")}-${crypto.randomUUID().slice(0,8)}`,category,price:Math.round(n*100)/100,compare_at_price:old,stock:s,description:description.trim(),image_url:image||null,sku:sku||null,weight_label:weight||null,ingredients:ingredients||null,allergens:allergens||null,badge:badge||null,featured,is_active:active,purchase_mode:mode},p?.id);await onSaved();toast.success(p?"Articolo aggiornato":"Nuovo articolo aggiunto al catalogo");onClose();}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
  return <Dialog open onOpenChange={v=>!v&&!busy&&onClose()}><DialogContent className="editor-modal modal" showCloseButton={!busy} onInteractOutside={e=>busy&&e.preventDefault()} onEscapeKeyDown={e=>busy&&e.preventDefault()}><span className="eyebrow">GESTIONE CATALOGO</span><DialogTitle>{p?"Modifica articolo":"Aggiungi un nuovo articolo"}</DialogTitle><DialogDescription>Dolci, snack, bibite o attrezzature: scegli la categoria e la modalità di vendita.</DialogDescription><form className="form-stack" onSubmit={submit}><div className="form-grid"><Field label="Nome articolo *"><Input value={name} required minLength={2} maxLength={200} onChange={e=>setName(e.target.value)}/></Field><Field label="Categoria *"><Input list="jolly-categories" value={category} onChange={e=>setCategory(e.target.value)} required maxLength={80}/><datalist id="jolly-categories">{CATEGORIES.slice(1).map(c=><option key={c} value={c}/>)}</datalist></Field><Field label="Modalità di vendita"><NativeSelect value={mode} onChange={e=>setMode(e.target.value as "buy"|"quote")}><Option value="buy">Acquisto dal catalogo</Option><Option value="quote">Solo su preventivo</Option></NativeSelect></Field><Field label="Disponibilità in magazzino *"><Input type="number" min={0} max={1000000} step={1} required value={stock} onChange={e=>setStock(e.target.value)}/></Field><Field label={mode==="quote"?"Prezzo indicativo interno (€)":"Prezzo di vendita (€) *"}><Input inputMode="decimal" required={mode==="buy"} value={price} onChange={e=>setPrice(e.target.value)} placeholder="8,90"/></Field><Field label="Prezzo precedente (€, facoltativo)"><Input inputMode="decimal" value={oldPrice} onChange={e=>setOldPrice(e.target.value)} placeholder="Solo se realmente applicato"/></Field><Field label="Codice articolo / SKU"><Input value={sku} maxLength={80} onChange={e=>setSku(e.target.value)}/></Field><Field label="Formato / confezione"><Input value={weight} maxLength={80} onChange={e=>setWeight(e.target.value)} placeholder="Es. 250 g · Cartone 24 lattine"/></Field></div><Field label="Descrizione *"><textarea value={description} required maxLength={5000} onChange={e=>setDescription(e.target.value)} placeholder="Descrivi il prodotto o le caratteristiche della macchina…"/></Field>
    <div className="image-upload"><div className="upload-preview">{safeImage(image)?<img src={image} alt="Anteprima articolo"/>:<Upload size={32}/>}</div><div className="form-stack"><Field label="URL immagine (oppure caricala sotto)"><Input value={image} onChange={e=>setImage(e.target.value)} placeholder="https://…"/></Field><label className="upload-label"><Upload size={17}/> Carica immagine<Input type="file" accept="image/png,image/jpeg,image/webp" disabled={busy} onChange={async e=>{const file=e.target.files?.[0];if(!file)return;setBusy(true);setError("");try{setImage(await api.upload(file));toast.success("Immagine caricata");}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}}/></label><small className="muted">JPG, PNG o WebP · massimo 5 MB</small></div></div>
    <div className="form-grid"><Field label="Ingredienti / specifiche tecniche"><textarea value={ingredients} maxLength={5000} onChange={e=>setIngredients(e.target.value)}/></Field><Field label="Allergeni / avvertenze"><textarea value={allergens} maxLength={2000} onChange={e=>setAllergens(e.target.value)}/></Field></div><Field label="Etichetta facoltativa"><Input value={badge} maxLength={35} onChange={e=>setBadge(e.target.value)} placeholder="Es. Novità"/></Field><div className="inline-checks"><label className="check-label"><Checkbox checked={featured} onCheckedChange={v=>setFeatured(v===true)}/> In evidenza</label><label className="check-label"><Checkbox checked={active} onCheckedChange={v=>setActive(v===true)}/> Visibile ai clienti</label></div>{error&&<p className="notice error" role="alert">{error}</p>}<div className="modal-actions"><Button className="btn btn-outline" type="button" disabled={busy} onClick={onClose}>Annulla</Button><Button className="btn" disabled={busy}>{busy?"Salvataggio…":p?"Salva modifiche":"Aggiungi articolo"}<Check size={17}/></Button></div></form></DialogContent></Dialog>;
}
function UserEditor({ api,user:u,self,onClose,onSaved }: { api:ShopApi;user:Profile;self:boolean;onClose:()=>void;onSaved:()=>Promise<void> }) {
  const [p,setP]=useState(u);const [busy,setBusy]=useState(false);const [error,setError]=useState("");
  return <Dialog open onOpenChange={v=>!v&&!busy&&onClose()}><DialogContent className="modal user-modal"><span className="eyebrow">GESTIONE UTENTI</span><DialogTitle>{u.full_name}</DialogTitle><DialogDescription>{u.email}. Lo staff può gestire il catalogo, gli ordini e gli altri utenti.</DialogDescription><form className="form-stack" onSubmit={async e=>{e.preventDefault();setBusy(true);setError("");try{await api.staffUser(p);await onSaved();toast.success("Utente aggiornato");onClose();}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}}><Field label="Nome e cognome"><Input required minLength={2} maxLength={120} value={p.full_name} onChange={e=>setP({...p,full_name:e.target.value})}/></Field><Field label="Telefono"><Input type="tel" maxLength={40} value={p.phone||""} onChange={e=>setP({...p,phone:e.target.value})}/></Field><Field label="Ruolo"><NativeSelect value={p.role} disabled={self} onChange={e=>setP({...p,role:e.target.value as Profile["role"]})}><Option value="customer">Cliente</Option><Option value="staff">Staff — gestione completa</Option></NativeSelect></Field><label className="setting-toggle"><span><b>Account sospeso</b><small>Blocca l’accesso ai dati senza eliminare lo storico.</small></span><Switch checked={!!p.is_blocked} disabled={self} onCheckedChange={v=>setP({...p,is_blocked:v})}/></label>{self&&<p className="muted small">Non puoi sospendere te stesso o rimuovere il tuo ruolo staff.</p>}{error&&<p className="notice error" role="alert">{error}</p>}<Button className="btn" disabled={busy}>{busy?"Salvataggio…":"Salva utente"}</Button><button className="text-button" type="button" disabled={busy||!u.email} onClick={async()=>{setBusy(true);try{await api.reset(u.email!);toast.success("Email per il recupero password inviata");}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}}>Invia email di recupero password</button></form></DialogContent></Dialog>;
}
export function Admin({ api,profile,products,orders,settings,onRefresh,onBack }: { api:ShopApi;profile:Profile;products:Product[];orders:Order[];settings:Settings;onRefresh:()=>Promise<void>;onBack:()=>void }) {
  const [tab,setTab]=useState("overview");const [search,setSearch]=useState("");const [editor,setEditor]=useState<Product|null|undefined>(undefined);const [userEditor,setUserEditor]=useState<Profile|null>(null);
  const [users,setUsers]=useState<Profile[]>([]);const [coupons,setCoupons]=useState<Coupon[]>([]);const [quotes,setQuotes]=useState<Quote[]>([]);const [config,setConfig]=useState(settings);const [busy,setBusy]=useState(false);const [detail,setDetail]=useState<Order|null>(null);const [orderEdit,setOrderEdit]=useState<Order|null>(null);const [markPaid,setMarkPaid]=useState(false);
  const [invite,setInvite]=useState(false);const [inviteEmail,setInviteEmail]=useState("");const [inviteName,setInviteName]=useState("");const [inviteRole,setInviteRole]=useState("customer");const [inviteError,setInviteError]=useState("");
  const [coupon,setCoupon]=useState<Coupon>({code:"",percent_off:10,min_amount:0,expires_at:null,is_active:true});const [statusFilter,setStatusFilter]=useState("all");
  const reloadAdmin=useCallback(async()=>{const[u,c,q]=await Promise.all([api.users(),api.coupons(),api.quotes()]);setUsers(u);setCoupons(c);setQuotes(q);},[api]);
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(()=>{reloadAdmin().catch(e=>toast.error(errorMessage(e)));},[reloadAdmin]);
  async function action(fn:()=>Promise<unknown>){setBusy(true);try{await fn();}catch(e){toast.error(errorMessage(e));}finally{setBusy(false);}}
  const nav=[{id:"overview",label:"Panoramica",Icon:LayoutDashboard},{id:"products",label:"Articoli",Icon:Boxes},{id:"orders",label:"Ordini",Icon:ClipboardList},{id:"users",label:"Utenti",Icon:Users},{id:"quotes",label:"Preventivi",Icon:Package},{id:"coupons",label:"Promozioni",Icon:BadgePercent},{id:"settings",label:"Negozio",Icon:Settings2}];
  const low=products.filter(p=>p.is_active&&p.purchase_mode!=="quote"&&p.stock<=5);
  const filteredProducts=products.filter(p=>`${p.name} ${p.category} ${p.sku||""}`.toLowerCase().includes(search.toLowerCase()));
  const filteredUsers=users.filter(p=>`${p.full_name} ${p.email}`.toLowerCase().includes(search.toLowerCase()));
  const filteredOrders=orders.filter(o=>(statusFilter==="all"||o.status===statusFilter)&&`${orderNumber(o.id)} ${o.customer_email} ${o.shipping_address?.full_name||""}`.toLowerCase().includes(search.toLowerCase()));
  const paid=orders.filter(o=>o.payment_status==="paid").reduce((s,o)=>s+Number(o.total_amount),0);
  return <div className="admin-shell"><aside className="admin-sidebar"><Brand small/><div className="staff-label"><ShieldCheck size={16}/> AREA STAFF</div><nav>{nav.map(({id,label,Icon})=><button className={tab===id?"active":""} key={id} onClick={()=>{setTab(id);setSearch("");}}><Icon size={19}/><span>{label}</span>{id==="orders"&&orders.filter(o=>o.status==="pending").length>0&&<b>{orders.filter(o=>o.status==="pending").length}</b>}</button>)}</nav><button className="admin-back" onClick={onBack}><ArrowLeft size={18}/> Torna al negozio</button><p className="muted small">{profile.full_name}</p></aside><main className="admin-main"><div className="admin-top"><div><span className="eyebrow">JOLLY CONTROL ROOM</span><h1>{nav.find(n=>n.id===tab)?.label}</h1></div><Button className="btn btn-outline" disabled={busy} onClick={()=>action(async()=>{await Promise.all([onRefresh(),reloadAdmin()]);toast.success("Dati aggiornati");})}><RefreshCw size={16}/> Aggiorna</Button></div>
    {tab==="overview"&&<><div className="dashboard-welcome"><div><span className="eyebrow">TUTTO SOTTO CONTROLLO</span><h2>Un buon assortimento.<br/>Una gestione ancora migliore.</h2><p>Nuovi ordini, disponibilità e clienti. Il tuo negozio, a colpo d’occhio.</p></div><Button className="btn" onClick={()=>setEditor(null)}>Nuovo articolo <Plus size={18}/></Button></div><div className="stat-grid"><div><span>Incassato</span><strong>{money(paid)}</strong><small>Ordini con pagamento confermato</small></div><div><span>Da confermare</span><strong>{orders.filter(o=>o.status==="pending").length}</strong><small>Ordini da controllare</small></div><div><span>Articoli attivi</span><strong>{products.filter(p=>p.is_active).length}</strong><small>Visibili nel catalogo</small></div><div><span>Clienti</span><strong>{users.filter(u=>u.role==="customer").length}</strong><small>Account registrati</small></div></div><div className="dashboard-columns"><section className="panel"><div className="section-title"><h2>Ultimi ordini</h2><button className="text-button" onClick={()=>setTab("orders")}>Tutti <ArrowUpRight size={16}/></button></div>{orders.length?orders.slice(0,5).map(o=><button className="activity-row" key={o.id} onClick={()=>setDetail(o)}><span><b>{orderNumber(o.id)}</b><small>{o.shipping_address?.full_name||o.customer_email}</small></span><span><b>{money(Number(o.total_amount))}</b><small>{ORDER_STATUS[o.status]}</small></span></button>):<p className="muted">I nuovi ordini appariranno qui.</p>}</section><section className="panel"><div className="section-title"><h2>Da rifornire</h2><span className="count-pill">{low.length}</span></div>{low.length?low.slice(0,6).map(p=><button className="activity-row" key={p.id} onClick={()=>setEditor(p)}><span><b>{p.name}</b><small>{p.category}</small></span><span className="stock-warning">{p.stock} pezzi</span></button>):<p className="muted">Nessun articolo sotto la soglia di 6 pezzi.</p>}</section></div></>}
    {tab==="products"&&<><div className="admin-toolbar"><div className="search-field"><Search size={18}/><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Cerca nome, categoria, SKU…"/></div><Button className="btn btn-outline" onClick={()=>downloadCsv("jolly-articoli.csv",[["Nome","SKU","Categoria","Prezzo","Stock","Attivo","Vendita"],...filteredProducts.map(p=>[p.name,p.sku,p.category,p.price,p.stock,p.is_active,p.purchase_mode])])}><Download size={17}/> Esporta</Button><Button className="btn" onClick={()=>setEditor(null)}><Plus size={17}/> Aggiungi articolo</Button></div><div className="table-scroll"><table className="admin-table"><thead><tr><th>Articolo</th><th>Categoria</th><th>Prezzo</th><th>Stock</th><th>Visibilità</th><th><span className="sr-only">Azioni</span></th></tr></thead><tbody>{filteredProducts.map(p=><tr key={p.id}><td><div className="table-product"><ProductImage product={p}/><span><b>{p.name}</b><small>{p.sku||p.weight_label||"—"}</small></span></div></td><td>{p.category}</td><td>{p.purchase_mode==="quote"?"Preventivo":money(Number(p.price))}</td><td><span className={p.stock<=5?"stock-warning":""}>{p.stock}</span></td><td><span className={`status-tag ${p.is_active?"status-confirmed":"status-cancelled"}`}>{p.is_active?"Visibile":"Nascosto"}</span></td><td><Button className="btn btn-outline" onClick={()=>setEditor(p)}><Pencil size={15}/> Modifica</Button></td></tr>)}</tbody></table>{filteredProducts.length===0&&<Empty title="Nessun articolo trovato" description="Aggiungi il tuo primo prodotto o modifica la ricerca." action={<Button className="btn" onClick={()=>setEditor(null)}>Aggiungi articolo</Button>}/>}</div></>}
    {tab==="users"&&<><p className="muted">Gestisci ruoli e accessi senza uscire dal sito. Il blocco di un account conserva ordini e dati.</p><div className="admin-toolbar"><div className="search-field"><Search size={18}/><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Cerca nome o email…"/></div><Button className="btn" onClick={()=>{setInvite(true);setInviteError("");}}><MailPlus size={18}/> Invita utente</Button></div><div className="table-scroll"><table className="admin-table"><thead><tr><th>Utente</th><th>Ruolo</th><th>Stato</th><th>Iscrizione</th><th><span className="sr-only">Azioni</span></th></tr></thead><tbody>{filteredUsers.map(u=><tr key={u.id}><td><b>{u.full_name}</b><small>{u.email}</small></td><td>{u.role==="staff"?"Staff":"Cliente"}</td><td><span className={`status-tag ${u.is_blocked?"status-cancelled":"status-confirmed"}`}>{u.is_blocked?"Sospeso":"Attivo"}</span></td><td>{u.created_at?date(u.created_at):"—"}</td><td><Button className="btn btn-outline" onClick={()=>setUserEditor(u)}><Pencil size={15}/> Gestisci</Button></td></tr>)}</tbody></table></div></>}
    {tab==="orders"&&<><div className="admin-toolbar"><div className="search-field"><Search size={18}/><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Cerca numero ordine, nome o email…"/></div><NativeSelect aria-label="Filtra stato ordine" value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><Option value="all">Tutti gli stati</Option>{Object.entries(ORDER_STATUS).map(([k,v])=><Option key={k} value={k}>{v}</Option>)}</NativeSelect><Button className="btn btn-outline" onClick={()=>downloadCsv("jolly-ordini.csv",[["Ordine","Data","Cliente","Email","Stato","Pagamento","Totale"],...filteredOrders.map(o=>[orderNumber(o.id),date(o.created_at),o.shipping_address?.full_name,o.customer_email,ORDER_STATUS[o.status],PAYMENT_STATUS[o.payment_status],o.total_amount])])}><Download size={17}/> CSV</Button></div><div className="table-scroll"><table className="admin-table"><thead><tr><th>Ordine</th><th>Cliente</th><th>Totale</th><th>Stato</th><th>Pagamento</th><th>Azioni</th></tr></thead><tbody>{filteredOrders.map(o=><tr key={o.id}><td><b>{orderNumber(o.id)}</b><small>{date(o.created_at)}</small></td><td><b>{o.shipping_address?.full_name||"Cliente"}</b><small>{o.customer_email}</small></td><td>{money(Number(o.total_amount))}</td><td><span className={`status-tag status-${o.status}`}>{ORDER_STATUS[o.status]}</span></td><td>{PAYMENT_STATUS[o.payment_status]}</td><td><div className="row-actions"><button className="icon-btn" aria-label="Dettaglio ordine" onClick={()=>setDetail(o)}><Eye size={17}/></button><button className="icon-btn" aria-label="Gestisci ordine" onClick={()=>{setOrderEdit(o);setMarkPaid(false);}}><Pencil size={17}/></button></div></td></tr>)}</tbody></table>{filteredOrders.length===0&&<Empty title="Nessun ordine" description="I nuovi ordini dei clienti appariranno qui."/>}</div></>}
    {tab==="quotes"&&<div className="account-orders">{quotes.length?quotes.map(q=><article className="order-card" key={q.id}><div className="order-card-top"><div><span className="eyebrow">{date(q.created_at)}</span><h3>{q.product_name}</h3></div><NativeSelect aria-label="Stato richiesta" value={q.status} disabled={busy} onChange={e=>action(async()=>{await api.updateQuote(q.id,e.target.value);await reloadAdmin();})}><Option value="new">Da gestire</Option><Option value="contacted">In contatto</Option><Option value="closed">Chiusa</Option></NativeSelect></div><p>{q.message}</p><div className="muted">{users.find(u=>u.id===q.user_id)?.full_name||"Cliente"} · {users.find(u=>u.id===q.user_id)?.email} · {q.phone}</div></article>):<Empty title="Nessuna richiesta di preventivo" description="Le richieste per le attrezzature verranno raccolte qui."/>}</div>}
    {tab==="coupons"&&<div className="profile-grid"><form className="panel form-stack" onSubmit={e=>{e.preventDefault();action(async()=>{await api.saveCoupon(coupon);await reloadAdmin();toast.success("Promozione salvata");});}}><h2>Crea o modifica un codice</h2><Field label="Codice sconto"><Input required minLength={3} maxLength={30} value={coupon.code} onChange={e=>setCoupon({...coupon,code:e.target.value.toUpperCase().replace(/[^A-Z0-9_-]/g,"")})} placeholder="Es. PAUSA10"/></Field><div className="form-grid"><Field label="Sconto (%)"><Input type="number" min={1} max={90} required value={coupon.percent_off} onChange={e=>setCoupon({...coupon,percent_off:Number(e.target.value)})}/></Field><Field label="Spesa minima (€)"><Input type="number" min={0} step="0.01" required value={coupon.min_amount} onChange={e=>setCoupon({...coupon,min_amount:Number(e.target.value)})}/></Field></div><Field label="Scadenza (facoltativa)"><Input type="date" value={coupon.expires_at?coupon.expires_at.slice(0,10):""} onChange={e=>setCoupon({...coupon,expires_at:e.target.value?new Date(e.target.value+"T23:59:59").toISOString():null})}/></Field><label className="check-label"><Checkbox checked={coupon.is_active} onCheckedChange={v=>setCoupon({...coupon,is_active:v===true})}/> Codice attivo</label><Button className="btn" disabled={busy}>Salva codice</Button><p className="muted small">Riutilizzabile fino alla scadenza. Non cumulabile con altri codici.</p></form><section className="panel"><h2>I tuoi codici</h2>{coupons.map(c=><button className="activity-row" key={c.code} onClick={()=>setCoupon(c)}><span><b>{c.code}</b><small>{c.is_active?"Attivo":"Disattivato"} · minimo {money(Number(c.min_amount))}</small></span><strong>−{c.percent_off}%</strong></button>)}{!coupons.length&&<p className="muted">Non hai ancora creato promozioni.</p>}</section></div>}
    {tab==="settings"&&<form className="panel settings-form form-stack" onSubmit={e=>{e.preventDefault();action(async()=>{await api.saveSettings(config);await onRefresh();toast.success("Impostazioni salvate");});}}><h2>Spedizioni e ritiro</h2><div className="form-grid"><Field label="Costo spedizione (€)"><Input type="number" min={0} step="0.01" required value={config.shipping_fee} onChange={e=>setConfig({...config,shipping_fee:Number(e.target.value)})}/></Field><Field label="Spedizione gratuita da (€)"><Input type="number" min={0} step="0.01" required value={config.free_shipping_threshold} onChange={e=>setConfig({...config,free_shipping_threshold:Number(e.target.value)})}/></Field></div><label className="setting-toggle"><span><b>Consenti il ritiro in sede</b><small>Alternativa alla spedizione, senza costi aggiuntivi.</small></span><Switch checked={config.pickup_enabled} onCheckedChange={v=>setConfig({...config,pickup_enabled:v})}/></label><Field label="Indirizzo e indicazioni per il ritiro"><Input required={config.pickup_enabled} value={config.pickup_address} maxLength={500} onChange={e=>setConfig({...config,pickup_address:e.target.value})}/></Field><h2>Pagamenti</h2><label className="setting-toggle"><span><b>Bonifico bancario</b><small>Confermi l’incasso manualmente dopo la verifica.</small></span><Switch checked={config.bank_enabled} onCheckedChange={v=>setConfig({...config,bank_enabled:v})}/></label><Field label="Coordinate e istruzioni bonifico"><textarea required={config.bank_enabled} maxLength={2000} value={config.bank_details} onChange={e=>setConfig({...config,bank_details:e.target.value})} placeholder="Intestatario, IBAN e istruzioni"/></Field><label className="setting-toggle"><span><b>Pagamento con carta (Stripe)</b><small>Attiva solo dopo aver configurato chiavi e webhook su Cloudflare: vedi la guida nello ZIP.</small></span><Switch checked={config.card_enabled} onCheckedChange={v=>setConfig({...config,card_enabled:v})}/></label><h2>Contatti e comunicazioni</h2><div className="form-grid"><Field label="Email assistenza"><Input type="email" value={config.contact_email} onChange={e=>setConfig({...config,contact_email:e.target.value})}/></Field><Field label="Telefono assistenza"><Input type="tel" value={config.contact_phone} onChange={e=>setConfig({...config,contact_phone:e.target.value})}/></Field></div><Field label="Messaggio in alto nel negozio"><Input value={config.announcement} maxLength={140} onChange={e=>setConfig({...config,announcement:e.target.value})}/></Field><Button className="btn" disabled={busy}>Salva impostazioni <Check size={18}/></Button></form>}
  </main>
    {editor!==undefined&&<ProductEditor api={api} product={editor} onClose={()=>setEditor(undefined)} onSaved={onRefresh}/>}{userEditor&&<UserEditor api={api} user={userEditor} self={userEditor.id===profile.id} onClose={()=>setUserEditor(null)} onSaved={reloadAdmin}/>}{detail&&<OrderDetail order={detail} settings={settings} onClose={()=>setDetail(null)}/>}
    <Dialog open={invite} onOpenChange={v=>!busy&&setInvite(v)}><DialogContent className="modal"><DialogTitle>Invita un nuovo utente</DialogTitle><DialogDescription>Riceverà un’email per scegliere la sua password. Non è necessario comunicarne una allo staff.</DialogDescription><form className="form-stack" onSubmit={async e=>{e.preventDefault();setBusy(true);setInviteError("");try{await api.server("/api/admin-users",{email:inviteEmail,name:inviteName,role:inviteRole});await reloadAdmin();toast.success("Invito inviato");setInvite(false);setInviteEmail("");setInviteName("");}catch(e){setInviteError(errorMessage(e));}finally{setBusy(false);}}}><Field label="Nome e cognome"><Input required minLength={2} maxLength={120} value={inviteName} onChange={e=>setInviteName(e.target.value)}/></Field><Field label="Email"><Input type="email" required maxLength={254} value={inviteEmail} onChange={e=>setInviteEmail(e.target.value)}/></Field><Field label="Ruolo"><NativeSelect value={inviteRole} onChange={e=>setInviteRole(e.target.value)}><Option value="customer">Cliente</Option><Option value="staff">Staff</Option></NativeSelect></Field>{inviteError&&<p className="notice error" role="alert">{inviteError}</p>}<Button className="btn" disabled={busy}>{busy?"Invio…":"Invia invito"}<MailPlus size={17}/></Button></form></DialogContent></Dialog>
    <Dialog open={!!orderEdit} onOpenChange={v=>!v&&!busy&&setOrderEdit(null)}><DialogContent className="modal"><DialogTitle>Gestisci {orderEdit&&orderNumber(orderEdit.id)}</DialogTitle><DialogDescription>Aggiorna lo stato e, se presente, il collegamento del corriere.</DialogDescription>{orderEdit&&<form className="form-stack" onSubmit={async e=>{e.preventDefault();setBusy(true);try{await api.staffOrder(orderEdit.id,orderEdit.status,orderEdit.tracking_url||"",markPaid);await onRefresh();toast.success("Ordine aggiornato");setOrderEdit(null);}catch(e){toast.error(errorMessage(e));}finally{setBusy(false);}}}><Field label="Stato ordine"><NativeSelect value={orderEdit.status} onChange={e=>setOrderEdit({...orderEdit,status:e.target.value})}>{Object.entries(ORDER_STATUS).map(([k,v])=><Option key={k} value={k}>{v}</Option>)}</NativeSelect></Field><Field label="Link tracking HTTPS"><Input type="url" value={orderEdit.tracking_url||""} onChange={e=>setOrderEdit({...orderEdit,tracking_url:e.target.value})} placeholder="https://…"/></Field>{orderEdit.payment_provider!=="stripe"&&orderEdit.payment_status!=="paid"&&<label className="check-label"><Checkbox checked={markPaid} onCheckedChange={v=>setMarkPaid(v===true)}/> Confermo di aver verificato e ricevuto il pagamento</label>}{orderEdit.status==="cancelled"&&<p className="notice">L’annullamento reintegra lo stock. Per gli ordini già pagati serve prima gestire il rimborso; gli ordini Stripe scadono automaticamente se non pagati.</p>}<Button className="btn" disabled={busy}>Salva stato ordine</Button></form>}</DialogContent></Dialog>
  </div>;
}
