"use client";
import {useEffect,useState} from "react";
import {ShopApi,errorMessage} from "@/lib/supabase";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Field} from "./shared";
import {toast} from "sonner";
type Legal={id:number;business_name:string;registered_address:string;vat_number:string;contact_email:string;privacy_text:string;terms_text:string;updated_at?:string};
type Status={configured:{supabase:boolean;email:boolean;stripe:boolean};mails:{status:string;attempts:number;last_error:string|null;created_at:string}[]};
export function SystemPanel({api}:{api:ShopApi}){
 const [legal,setLegal]=useState<Legal|null>(null),[status,setStatus]=useState<Status|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
 async function load(){setError("");try{
  const l=await api.request<Legal[]>("/rest/v1/legal_settings?select=*&id=eq.1");setLegal(l[0]);
  const r=await fetch("/api/system",{headers:{Authorization:`Bearer ${await api.token()}`},cache:"no-store"});const s=await r.json() as Status & {error?:string};if(!r.ok)throw new Error(s.error);setStatus(s);
 }catch(e){setError(errorMessage(e));}}
 useEffect(()=>{load();},[api]);
 return <div className="form-stack"><section className="panel form-stack"><h2>Servizi e notifiche</h2><p>Le email vengono elaborate automaticamente ogni cinque minuti dopo aver configurato il server.</p>{error&&<p className="notice error">{error}</p>}{status&&<><div className="stat-grid">{Object.entries(status.configured).map(([key,ok])=><div key={key}><b>{key==="supabase"?"Gestione inviti":key==="email"?"Email automatiche":"Pagamenti Stripe"}</b><p>{ok?"Credenziali configurate":"Da configurare su Cloudflare"}</p></div>)}</div><p className="muted">La presenza delle credenziali non verifica il mittente email o il webhook Stripe. Controlla il risultato con un ordine di prova.</p><div className="table-scroll"><table className="admin-table"><thead><tr><th>Ultime 30 email</th><th>Tentativi</th><th>Dettaglio</th></tr></thead><tbody>{status.mails.map((m,i)=><tr key={i}><td>{({pending:"In attesa",processing:"Invio in corso",sent:"Inviata",failed:"Invio fallito"})[m.status]||m.status}</td><td>{m.attempts}</td><td>{m.last_error||new Date(m.created_at).toLocaleString("it-IT")}</td></tr>)}</tbody></table></div></>}<div className="card-actions"><Button className="btn btn-outline" disabled={busy} onClick={load}>Aggiorna stato</Button><Button className="btn" disabled={busy} onClick={async()=>{setBusy(true);try{const r=await api.server<{sent:number;failed:number}>("/api/system",{});toast.info(`${r.sent} email inviate, ${r.failed} da ritentare`);await load();}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}}>Elabora email in attesa</Button><Button className="btn btn-outline" disabled={busy} onClick={async()=>{if(!window.confirm("Ritentare le email fallite? Dopo oltre 24 ore un invio dall’esito incerto potrebbe arrivare due volte."))return;setBusy(true);try{await api.rpc("retry_failed_emails");await load();toast.success("Invii rimessi in coda");}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}}>Ritenta invii falliti</Button></div></section>
 {legal&&<form className="panel form-stack" onSubmit={async e=>{e.preventDefault();setBusy(true);try{await api.request("/rest/v1/legal_settings?id=eq.1",{method:"PATCH",body:JSON.stringify({...legal,updated_at:new Date().toISOString()})});toast.success("Informazioni pubbliche aggiornate");}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}}><h2>Informazioni aziendali e pagine legali</h2><p>Questi testi sono pubblici. Inserisci i dati reali dell’azienda e i testi approvati per il tuo negozio.</p>{([['business_name','Ragione sociale'],['registered_address','Sede legale'],['vat_number','Partita IVA'],['contact_email','Email di contatto']] as const).map(([key,label])=><Field key={key} label={label}><Input value={legal[key]} type={key==="contact_email"?"email":"text"} onChange={e=>setLegal({...legal,[key]:e.target.value})} required maxLength={500}/></Field>)}{([['privacy_text','Informativa privacy completa'],['terms_text','Condizioni di vendita complete']] as const).map(([key,label])=><Field key={key} label={label}><textarea rows={12} value={legal[key]} required maxLength={30000} onChange={e=>setLegal({...legal,[key]:e.target.value})}/></Field>)}<Button className="btn" disabled={busy}>Salva e pubblica i testi</Button></form>}
 </div>;
}
