"use client";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { ArrowRight, ArrowUpRight, Check, ChevronDown, Heart, LayoutGrid, Loader2, Menu, Package, RefreshCw, Search, Settings2, ShieldCheck, ShoppingBag, SlidersHorizontal, Sparkles, Trash2, Truck, UserRound, X } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Checkbox } from "@/components/ui/checkbox";
import { NativeSelect, NativeSelectOption as Option } from "@/components/ui/native-select";
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription } from "@/components/ui/sheet";
import { Toaster } from "@/components/ui/sonner";
import { ShopApi, getConfig, errorMessage } from "@/lib/supabase";
import { type CartEntry, type CartLine, type Order, type Product, type Profile, type Settings, CATEGORIES, DEFAULT_SETTINGS, lineUnitPrice, money, priceFor, totals } from "@/lib/shop";
import { Auth, PasswordSetup } from "@/components/shop/auth";
import { Brand, CategoryIcon, Empty, ProductCard, ProductImage, ProductModal, Quantity } from "@/components/shop/shared";
import { Checkout } from "@/components/shop/checkout";
import { Account } from "@/components/shop/account";
import { Admin } from "@/components/shop/admin";
import { WelcomeHub } from "@/components/shop/hub";

export default function Home() {
  const [api,setApi]=useState<ShopApi|null>(null);const [profile,setProfile]=useState<Profile|null>(null);const [booting,setBooting]=useState(true);const [recovery,setRecovery]=useState(false);const [authError,setAuthError]=useState("");
  const [products,setProducts]=useState<Product[]>([]);const [entries,setEntries]=useState<CartEntry[]>([]);const [favorites,setFavorites]=useState<string[]>([]);const [orders,setOrders]=useState<Order[]>([]);const [settings,setSettings]=useState<Settings>(DEFAULT_SETTINGS);
  const [view,setView]=useState<"home"|"shop"|"wishlist"|"account"|"staff">("home");const [loading,setLoading]=useState(false);const [ready,setReady]=useState(false);const [error,setError]=useState("");
  const [category,setCategory]=useState("Tutto");const [query,setQuery]=useState("");const [sort,setSort]=useState("featured");const [inStock,setInStock]=useState(false);const [sale,setSale]=useState(false);const [maxPrice,setMaxPrice]=useState("");const [limit,setLimit]=useState(12);const [filters,setFilters]=useState(false);
  const [cartOpen,setCartOpen]=useState(false);const [checkout,setCheckout]=useState(false);const [detail,setDetail]=useState<Product|null>(null);const [menu,setMenu]=useState(false);const [cartBusy,setCartBusy]=useState(false);const cartLock=useRef(false);const favoriteLocks=useRef(new Set<string>());
  function normalizeProducts(list:Product[], user:Profile) { return list.map(raw=>{const p={...raw,price:Number(raw.price),compare_at_price:raw.compare_at_price===null?null:Number(raw.compare_at_price),business_price:raw.business_price===null||raw.business_price===undefined?null:Number(raw.business_price),vip_price:raw.vip_price===null||raw.vip_price===undefined?null:Number(raw.vip_price),stock:Number(raw.stock),low_stock_threshold:Number(raw.low_stock_threshold??5)};return {...p,price:user.role==="staff"?Number(raw.price):priceFor(p,user)};}); }
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(()=>{let active=true;const c=getConfig();if(!c){setBooting(false);return;}const a=new ShopApi(c);setApi(a);a.boot().then(r=>{if(active){setProfile(r.profile);setRecovery(r.recovery);}}).catch(e=>{if(active)setAuthError(errorMessage(e));}).finally(()=>{if(active)setBooting(false);});return()=>{active=false;};},[]);
  const refresh=useCallback(async()=>{
    if(!api?.session)return;
    const p=await api.profile();
    const [ps,cs,fs,os,ss]=await Promise.all([api.products(),api.cart(),api.wishlist(),api.orders(),api.settings()]);
    setProfile(p);setProducts(normalizeProducts(ps,p));setEntries(cs);setFavorites(fs);setOrders(os);setSettings(ss);setReady(true);setError("");
  },[api]);
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(()=>{if(!profile?.id||!api)return;setLoading(true);setReady(false);refresh().catch(e=>setError(errorMessage(e))).finally(()=>setLoading(false));},[profile?.id,api,refresh]);
  useEffect(()=>{if(!profile||!api)return;const focus=()=>{if(!cartLock.current)refresh().catch(e=>setError(errorMessage(e)));};const storage=(e:StorageEvent)=>{if(e.key==="jolly-session-v3"&&!e.newValue){api.session=null;setProfile(null);setEntries([]);setFavorites([]);setProducts([]);setOrders([]);setReady(false);setView("shop");}};window.addEventListener("focus",focus);window.addEventListener("storage",storage);return()=>{window.removeEventListener("focus",focus);window.removeEventListener("storage",storage);};},[api,profile,refresh]);
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(()=>{setLimit(12);},[category,query,sort,inStock,sale,maxPrice,view]);
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(()=>{if(ready&&new URLSearchParams(location.search).has("payment")){setView("account");toast.info("Lo stato del pagamento viene aggiornato dopo la conferma del provider. Se è ancora in attesa, premi Aggiorna.",{duration:7000});history.replaceState({},"",location.pathname);}},[ready]);
  const catalog=useMemo(()=>products.filter(p=>p.is_active),[products]);
  const lines:CartLine[]=entries.map(e=>({ ...e, product:products.find(p=>p.id===e.product_id)||{id:e.product_id,name:"Articolo non più disponibile",slug:"",category:"Catalogo",description:"Rimuovi questo articolo per continuare.",price:0,compare_at_price:null,image_url:null,badge:null,stock:0,featured:false,is_active:false} }));
  const count=entries.reduce((n,e)=>n+e.quantity,0);const sum=totals(lines,settings);
  const invalidCart=lines.some(l=>l.quantity>(l.product.available_stock??l.product.stock)||!l.product.is_active||l.product.purchase_mode==="quote");
  const categories=Array.from(new Set([...CATEGORIES,...catalog.map(p=>p.category)]));
  const filtered=useMemo(()=>{
    const q=query.trim().toLocaleLowerCase("it");
    const list=catalog.filter(p=>(category==="Tutto"||p.category===category)&&(!q||`${p.name} ${p.description} ${p.category} ${p.sku||""}`.toLocaleLowerCase("it").includes(q))&&(!inStock||(p.available_stock??p.stock)>0||p.purchase_mode==="quote")&&(!sale||(p.compare_at_price&&p.compare_at_price>p.price&&p.purchase_mode!=="quote"))&&(!maxPrice||(p.purchase_mode!=="quote"&&p.price<=Number(maxPrice)))&&(view!=="wishlist"||favorites.includes(p.id)));
    return list.sort((a,b)=>sort==="price-asc"?a.price-b.price:sort==="price-desc"?b.price-a.price:sort==="name"?a.name.localeCompare(b.name,"it"):sort==="new"?(b.created_at||"").localeCompare(a.created_at||""):Number(b.featured)-Number(a.featured));
  },[catalog,category,query,inStock,sale,maxPrice,view,favorites,sort]);
  function navigate(v:typeof view,c?:string){setView(v);setMenu(false);if(c){setCategory(c);setQuery("");setSale(false);setMaxPrice("");setInStock(false);}window.scrollTo({top:0,behavior:"smooth"});}
  function resetFilters(){setCategory("Tutto");setQuery("");setInStock(false);setSale(false);setMaxPrice("");}
  async function changeQuantity(id:string,quantity:number,add=false){
    if(!api||cartLock.current)return;const p=products.find(p=>p.id===id);const current=entries.find(e=>e.product_id===id)?.quantity||0;const target=add?current+quantity:quantity;
    if(!Number.isInteger(target)||target<0||target>99||(target>0&&(!p||!p.is_active||p.purchase_mode==="quote"||target>(p.available_stock??p.stock)))){toast.error("La quantità richiesta supera la disponibilità. Aggiorna il catalogo e riprova.");return;}
    cartLock.current=true;setCartBusy(true);
    try{const result=await api.setQuantity(id,target);setEntries(result);if(add)toast.success(`${quantity} × ${p?.name} aggiunti al carrello`,{action:{label:"Apri carrello",onClick:()=>setCartOpen(true)}});else if(target===0)toast.success("Articolo rimosso dal carrello");}
    catch(e){toast.error(errorMessage(e));try{const [ps,cs]=await Promise.all([api.products(),api.cart()]);setProducts(normalizeProducts(ps,profile!));setEntries(cs);}catch{/* Preserve the last known state; the original error is visible. */}}
    finally{cartLock.current=false;setCartBusy(false);}
  }
  async function favorite(id:string){if(!api||favoriteLocks.current.has(id))return;favoriteLocks.current.add(id);const active=!favorites.includes(id);try{await api.favorite(id,active);setFavorites(fs=>active?[...fs,id]:fs.filter(x=>x!==id));toast.success(active?"Salvato nei preferiti":"Rimosso dai preferiti");}catch(e){toast.error(errorMessage(e));}finally{favoriteLocks.current.delete(id);}}
  async function notifyStock(id:string){if(!api)return;try{await api.stockAlert(id,true);toast.success("Ti avviseremo quando tornerà disponibile");}catch(e){toast.error(errorMessage(e));}}
  // The URL is the deep-link entry point for product QR codes.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(()=>{if(!ready||!products.length)return;const slug=new URLSearchParams(location.search).get("product");if(slug){const product=products.find(p=>p.slug===slug);if(product){setView("shop");setDetail(product);history.replaceState({},"",location.pathname);}}},[ready,products]);
  async function logout(){if(!api)return;try{await api.signOut();}catch{toast.info("Sessione locale chiusa.");}finally{setProfile(null);setEntries([]);setFavorites([]);setProducts([]);setOrders([]);setReady(false);setView("home");setCartOpen(false);setCheckout(false);setDetail(null);}}
  async function reorder(o:Order){if(!api||cartLock.current)return;cartLock.current=true;setCartBusy(true);try{const ps=normalizeProducts(await api.products(),profile!);setProducts(ps);let cs=await api.cart();let added=0;let skipped=0;for(const l of o.order_items){const p=ps.find(p=>p.id===l.product_id&&p.is_active&&p.purchase_mode!=="quote");if(!p){skipped+=l.quantity;continue;}const current=cs.find(x=>x.product_id===p.id)?.quantity||0;const n=Math.min(l.quantity,Math.max(0,Math.min(p.available_stock??p.stock,99)-current));if(n){cs=await api.setQuantity(p.id,current+n);setEntries(cs);added+=n;}skipped+=l.quantity-n;}toast[skipped?"info":"success"](`${added} pezzi aggiunti al carrello${skipped?`. ${skipped} non disponibili o già al limite.`:"."}`);setCartOpen(true);}catch(e){toast.error(errorMessage(e));}finally{cartLock.current=false;setCartBusy(false);}}
  const notifications=<Toaster theme="light" position="bottom-right" richColors closeButton/>;
  if(booting)return <main className="loading-page"><Brand/><Loader2 className="spin" size={24}/><p>Un momento, entriamo nel mondo Jolly…</p></main>;
  if(!profile)return <>{notifications}<Auth api={api} onUser={setProfile} initialError={authError}/></>;
  if(recovery&&api)return <>{notifications}<PasswordSetup api={api} onDone={()=>{setRecovery(false);toast.success("Password salvata");}}/></>;
  if(!api)return null;
  if(view==="staff"&&profile.role==="staff"&&ready)return <>{notifications}<Admin api={api} profile={profile} products={products} orders={orders} settings={settings} onRefresh={refresh} onBack={()=>navigate("home")}/></>;
  if(view==="home")return <>{notifications}<WelcomeHub profile={profile} count={count} favorites={favorites.length} isStaff={profile.role==="staff"} onGo={(v,c)=>navigate(v,c)} onLogout={logout} error={error} loading={loading} onRetry={()=>{setLoading(true);refresh().catch(e=>setError(errorMessage(e))).finally(()=>setLoading(false));}}/></>;
  return <div className="storefront">{notifications}<a className="skip-link" href="#content">Vai al contenuto</a><div className="announcement"><span>{settings.announcement}</span><span><Truck size={14}/> Spedizione gratuita da {money(Number(settings.free_shipping_threshold))}</span></div><header className="site-header"><button className="brand-button" aria-label="Jolly, torna alla home" onClick={()=>navigate("home")}><Brand/></button><nav className="desktop-nav" aria-label="Navigazione principale"><button className={view==="shop"?"active":""} onClick={()=>navigate("shop","Tutto")}>Catalogo <ChevronDown size={14}/></button><button onClick={()=>navigate("shop","Snack e patatine")}>Snack</button><button onClick={()=>navigate("shop","Bibite")}>Bibite</button><button onClick={()=>navigate("shop","Attrezzature")}>Attrezzature</button></nav><div className="header-actions">{profile.role==="staff"&&<button className="staff-shortcut" onClick={()=>navigate("staff")}><Settings2 size={17}/><span>Area staff</span></button>}<button className="icon-btn desktop-action" aria-label="I tuoi preferiti" onClick={()=>{resetFilters();navigate("wishlist");}}><Heart size={21}/>{favorites.length>0&&<span className="notification-count">{favorites.length}</span>}</button><button className="icon-btn desktop-action" aria-label="Il tuo account" onClick={()=>navigate("account")}><UserRound size={21}/></button><button className="bag-button" onClick={()=>setCartOpen(true)} aria-label={`Apri carrello, ${count} articoli`}><ShoppingBag size={20}/><span className="bag-label">Carrello</span><b>{count}</b></button><button className="icon-btn mobile-menu-button" aria-label="Apri menu" onClick={()=>setMenu(true)}><Menu size={23}/></button></div></header>
    <main id="content">{error&&<div className="page-wrap"><div className="notice error data-error" role="alert"><div><b>Non siamo riusciti ad aggiornare il negozio.</b><p>{error}</p></div><Button className="btn btn-outline" disabled={loading} onClick={async()=>{setLoading(true);try{await refresh();}catch(e){setError(errorMessage(e));}finally{setLoading(false);}}}><RefreshCw size={17}/> Riprova</Button></div></div>}
    {!ready?<section className="page-wrap"><div className="catalog-skeleton" aria-busy={loading}>{loading?<><Loader2 className="spin" size={28}/><p>Caricamento del tuo catalogo…</p></>:<><Package size={32}/><h2>Completiamo la configurazione</h2><p>Il catalogo sarà disponibile dopo aver risolto il messaggio qui sopra.</p></>}</div></section>:view==="account"?<Account api={api} profile={profile} orders={orders} settings={settings} onProfile={setProfile} onRefresh={refresh} onReorder={reorder} onLogout={logout}/>:<>
      {view==="shop"&&category==="Tutto"&&!query&&!sale&&<section className="hero page-wrap"><div className="hero-inner"><div className="hero-copy"><span className="eyebrow"><Sparkles size={16}/> IL BUONO, IN TUTTE LE SUE FORME.</span><h1>Una pausa.<br/><em>Mille possibilità.</em></h1><p>Dolce o salato? Fresco o croccante?<br/>Trova il tuo assortimento, dalle piccole golosità alle grandi attrezzature.</p><a className="btn btn-lg" href="#catalogo">Esplora il catalogo <ArrowUpRight size={20}/></a><div className="hero-tags"><span>Dolci</span><span>Snack</span><span>Bibite</span><span>Attrezzature</span></div></div><div className="hero-visual"><img src="/assortment.png" alt="Assortimento illustrativo di dolci, snack e bevande" fetchPriority="high"/><div className="hero-stamp"><span>TUTTO IL</span><b>buono.</b><span>È QUI.</span></div></div></div></section>}
      <section className="catalog page-wrap" id="catalogo"><div className="catalog-heading"><div><span className="eyebrow">{view==="wishlist"?"LA TUA SELEZIONE":"IL CATALOGO JOLLY"}</span><h2>{view==="wishlist"?"I tuoi preferiti.":category!=="Tutto"?category:query?"Troviamo quello che cerchi.":"Di cosa hai voglia?"}</h2></div><span className="catalog-count">{filtered.length} articoli</span></div>
      <div className="category-rail" role="group" aria-label="Categorie">{categories.map(c=><button key={c} className={category===c?"category-chip selected":"category-chip"} aria-pressed={category===c} onClick={()=>setCategory(c)}>{c==="Tutto"?<LayoutGrid size={19}/>:<CategoryIcon category={c} size={19}/>}<span>{c}</span></button>)}</div>
      <div className="catalog-toolbar"><div className="search-field"><Search size={20}/><Input value={query} onChange={e=>setQuery(e.target.value)} aria-label="Cerca nel catalogo" placeholder="Cerca prodotti, gusti o codici articolo…"/>{query&&<button className="icon-btn" onClick={()=>setQuery("")} aria-label="Cancella ricerca"><X size={17}/></button>}</div><button className={`filter-button ${filters?"selected":""}`} onClick={()=>setFilters(!filters)} aria-expanded={filters} aria-controls="catalog-filters"><SlidersHorizontal size={18}/> Filtri{(inStock||sale||maxPrice)&&<span className="filter-active"/>}</button><NativeSelect aria-label="Ordina prodotti" value={sort} onChange={e=>setSort(e.target.value)}><Option value="featured">In evidenza</Option><Option value="new">Più recenti</Option><Option value="price-asc">Prezzo crescente</Option><Option value="price-desc">Prezzo decrescente</Option><Option value="name">Nome A–Z</Option></NativeSelect></div>
      {filters&&<div id="catalog-filters" className="filters-panel"><label className="check-label"><Checkbox checked={inStock} onCheckedChange={v=>setInStock(v===true)}/> Solo disponibili</label><label className="check-label"><Checkbox checked={sale} onCheckedChange={v=>setSale(v===true)}/> In promozione</label><label className="max-price">Prezzo massimo (€)<Input type="number" min={0} step="0.01" value={maxPrice} onChange={e=>setMaxPrice(e.target.value)} placeholder="Tutti"/></label><button className="text-button" onClick={resetFilters}>Azzera filtri</button></div>}
      {filtered.length?<><div className="product-grid">{filtered.slice(0,limit).map(p=><ProductCard key={p.id} product={p} inCart={entries.find(e=>e.product_id===p.id)?.quantity||0} favorite={favorites.includes(p.id)} busy={cartBusy} onOpen={()=>setDetail(p)} onAdd={q=>changeQuantity(p.id,q,true)} onFavorite={()=>favorite(p.id)} onNotify={()=>notifyStock(p.id)}/>)}</div>{filtered.length>limit&&<div className="load-more"><p>Stai vedendo {limit} di {filtered.length} articoli</p><Button className="btn btn-outline" onClick={()=>setLimit(limit+12)}>Mostra altri articoli <ArrowRight size={18}/></Button></div>}</>:<Empty icon={view==="wishlist"?<Heart size={34}/>:<Search size={34}/>} title={view==="wishlist"&&!favorites.length?"Le cose buone si tengono da parte.":"Nessun articolo trovato"} description={view==="wishlist"&&!favorites.length?"Tocca il cuore su un articolo per ritrovarlo qui, anche al prossimo accesso.":catalog.length?"Prova un’altra ricerca o modifica i filtri.":"Lo staff non ha ancora pubblicato articoli. Il catalogo verrà aggiornato qui."} action={<Button className="btn btn-outline" onClick={()=>{resetFilters();setView("shop");}}>Torna al catalogo</Button>}/>}
      </section>
      {view==="shop"&&<section className="professional-strip page-wrap"><div className="professional-inner"><div className="pro-symbol"><Package size={45}/></div><div><span className="eyebrow">PER LA TUA ATTIVITÀ</span><h2>Non solo cose buone.<br/>Anche ciò che serve per crearle.</h2><p>Macchine per gelati, granite e attrezzature. Scopri il catalogo o chiedi un preventivo allo staff.</p></div><Button className="btn btn-lime" onClick={()=>navigate("shop","Attrezzature")}>Scopri le attrezzature <ArrowUpRight size={19}/></Button></div></section>}
      <section className="service-strip page-wrap"><div><Truck size={24}/><span><b>Spedizioni in Italia</b><small>Gratuite da {money(Number(settings.free_shipping_threshold))}</small></span></div><div><ShoppingBag size={24}/><span><b>Il tuo carrello, sempre qui</b><small>Salvato nel tuo account</small></span></div><div><ShieldCheck size={24}/><span><b>Un’area tutta tua</b><small>Ordini e dati personali</small></span></div></section>
    </>}</main>
    <footer className="site-footer page-wrap"><div className="footer-top"><Brand/><p>Dolce. Salato. Jolly.<br/><span>Il tuo assortimento, in un solo posto.</span></p><div>{settings.contact_email&&<a href={`mailto:${settings.contact_email}`}>{settings.contact_email}</a>}{settings.contact_phone&&<a href={`tel:${settings.contact_phone.replace(/[^+0-9]/g,"")}`}>{settings.contact_phone}</a>}<button onClick={()=>navigate("account")}>Il mio account <ArrowUpRight size={15}/></button><span className="footer-links"><a href="/privacy">Privacy</a><a href="/termini">Condizioni di vendita</a></span></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Jolly Dolciumi</span><span>Catalogo riservato agli utenti registrati</span></div></footer>
    <nav className="mobile-bottom-nav" aria-label="Navigazione mobile"><button className={view==="shop"?"active":""} onClick={()=>navigate("shop")}><LayoutGrid size={20}/><span>Catalogo</span></button><button className={view==="wishlist"?"active":""} onClick={()=>{resetFilters();navigate("wishlist");}}><Heart size={20}/><span>Preferiti</span></button><button onClick={()=>setCartOpen(true)}><ShoppingBag size={20}/><span>Carrello ({count})</span></button><button className={view==="account"?"active":""} onClick={()=>navigate("account")}><UserRound size={20}/><span>Account</span></button></nav>
    <Sheet open={menu} onOpenChange={setMenu}><SheetContent className="menu-sheet"><SheetHeader><SheetTitle>Il mondo Jolly</SheetTitle><SheetDescription>Scegli dove vuoi andare.</SheetDescription></SheetHeader><nav>{CATEGORIES.map(c=><button key={c} onClick={()=>navigate("shop",c)}><CategoryIcon category={c}/>{c}<ArrowRight size={16}/></button>)}{profile.role==="staff"&&<button onClick={()=>navigate("staff")}><Settings2/> Area staff</button>}</nav><button className="text-button" onClick={logout}>Esci dall’account</button></SheetContent></Sheet>
    <Sheet open={cartOpen} onOpenChange={setCartOpen}><SheetContent className="cart-sheet"><SheetHeader className="cart-header"><span className="eyebrow">OTTIMA SCELTA.</span><SheetTitle>Il tuo carrello <span>{count}</span></SheetTitle><SheetDescription>Salvato nel tuo account, pronto quando vuoi.</SheetDescription></SheetHeader><div className="cart-scroll">{lines.length===0?<Empty title="Facciamo spazio al buono." description="Il carrello è vuoto. Aggiungi qualcosa dal catalogo per iniziare." action={<Button className="btn" onClick={()=>setCartOpen(false)}>Esplora il catalogo <ArrowRight size={18}/></Button>}/>:<><div className="shipping-progress"><p>{sum.subtotal>=Number(settings.free_shipping_threshold)?<><Check size={17}/> Hai raggiunto la spedizione gratuita!</>:<>Mancano <b>{money(Number(settings.free_shipping_threshold)-sum.subtotal)}</b> alla spedizione gratuita.</>}</p><progress max={Math.max(1,Number(settings.free_shipping_threshold))} value={sum.subtotal} aria-label="Avanzamento verso la spedizione gratuita"/></div><div className="cart-lines">{lines.map(l=><div className="cart-line" key={l.product_id}><ProductImage product={l.product}/><div className="cart-line-copy"><span className="product-category">{l.product.category}</span><b>{l.product.name}</b><small className={l.quantity>(l.product.available_stock??l.product.stock)||!l.product.is_active?"danger":"muted"}>{!l.product.is_active?"Non più disponibile":l.quantity>(l.product.available_stock??l.product.stock)?`Disponibilità cambiata: massimo ${l.product.stock}`:`${Math.max(0,l.product.stock-l.quantity)} ancora disponibili`}</small><div className="cart-line-controls"><Quantity value={l.quantity} min={0} max={l.product.available_stock??l.product.stock} onChange={q=>changeQuantity(l.product_id,q)} disabled={cartBusy} label={`Quantità ${l.product.name}`}/><strong>{money(lineUnitPrice(l.product,l.quantity)*l.quantity)}</strong></div></div><button className="remove-line icon-btn" disabled={cartBusy} onClick={()=>changeQuantity(l.product_id,0)} aria-label={`Rimuovi ${l.product.name} dal carrello`}><Trash2 size={16}/></button></div>)}</div></>}</div>{lines.length>0&&<div className="cart-footer"><div className="totals"><div><span>Subtotale</span><b>{money(sum.subtotal)}</b></div><div><span>Spedizione stimata</span><b>{sum.shipping?money(sum.shipping):"Gratuita"}</b></div><div className="grand-total"><span>Totale</span><strong>{money(sum.total)}</strong></div></div>{invalidCart&&<p className="notice error">Aggiorna le quantità o rimuovi gli articoli non disponibili.</p>}<Button className="btn full btn-lg" disabled={cartBusy||invalidCart||!ready} onClick={()=>{setCartOpen(false);setCheckout(true);}}>Vai al checkout <ArrowRight size={18}/></Button><p className="cart-note">Puoi applicare un codice sconto e scegliere la consegna al checkout. Lo stock viene riservato alla conferma dell’ordine.</p></div>}</SheetContent></Sheet>
    {checkout&&<Checkout api={api} profile={profile} lines={lines} settings={settings} onClose={()=>setCheckout(false)} onCreated={async()=>{setCheckout(false);setView("account");toast.success("Ordine creato! Trovi il riepilogo nel tuo account.");try{await refresh();}catch(e){setError(errorMessage(e));}window.scrollTo({top:0,behavior:"smooth"});}}/>}
    {detail&&<ProductModal key={detail.id} product={products.find(p=>p.id===detail.id)||detail} inCart={entries.find(e=>e.product_id===detail.id)?.quantity||0} busy={cartBusy} onClose={()=>setDetail(null)} onAdd={q=>changeQuantity(detail.id,q,true)} onNotify={()=>notifyStock(detail.id)} onQuote={async(message,phone)=>{try{await api.quote(detail,message,phone);toast.success("Richiesta inviata allo staff");setDetail(null);}catch(e){toast.error(errorMessage(e));}}}/>}
  </div>;
}
